### ISSUE TITLE
Does the model support frame interpolation at any timestep？

### ISSUE THREAD

**Issue by ryanqiutu** [danier97/LDMVFI#13]
Dear author：
      Great work！But I have a question. I want to know if the model support frame interpolation at any timestep. If I put the timestep as control, and concat it with the embeddings of frame1 & frame2，can the model support any timestep frame interpolation?

**Comment by danier97** [comment]
Hello. Thank you very much for your interest in the work. Due to the way the model is trained, it does not support passing in timestep as input and interpolating at any time. The model assumes the desired output timestep is the middle of the two frames. To achieve what you described, one would need to fine-tune/re-train for the new setting (with appropriate modification of the model).

Thank you.
